//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_User_Interface.RegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StarShipDTO", Namespace="http://schemas.datacontract.org/2004/07/StepWars.BusinessLogic.Clasess.DTO")]
    [System.SerializableAttribute()]
    public partial class StarShipDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF_User_Interface.RegistrationService.BonusDTO BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DamageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF_User_Interface.RegistrationService.BonusDTO Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((object.ReferenceEquals(this.BonusField, value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Damage {
            get {
                return this.DamageField;
            }
            set {
                if ((this.DamageField.Equals(value) != true)) {
                    this.DamageField = value;
                    this.RaisePropertyChanged("Damage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BonusDTO", Namespace="http://schemas.datacontract.org/2004/07/StepWars.BusinessLogic.Clasess.DTO")]
    [System.SerializableAttribute()]
    public partial class BonusDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/StepWars.BusinessLogic.Clasess.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminRulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF_User_Interface.RegistrationService.StarShipDTO ShipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AdminRules {
            get {
                return this.AdminRulesField;
            }
            set {
                if ((this.AdminRulesField.Equals(value) != true)) {
                    this.AdminRulesField = value;
                    this.RaisePropertyChanged("AdminRules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF_User_Interface.RegistrationService.StarShipDTO Ship {
            get {
                return this.ShipField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipField, value) != true)) {
                    this.ShipField = value;
                    this.RaisePropertyChanged("Ship");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationService.IRegistrationContract")]
    public interface IRegistrationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/GetAllShips", ReplyAction="http://tempuri.org/IRegistrationContract/GetAllShipsResponse")]
        WPF_User_Interface.RegistrationService.StarShipDTO[] GetAllShips();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/GetAllShips", ReplyAction="http://tempuri.org/IRegistrationContract/GetAllShipsResponse")]
        System.Threading.Tasks.Task<WPF_User_Interface.RegistrationService.StarShipDTO[]> GetAllShipsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToUserExist", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToUserExistResponse")]
        bool CheckToUserExist(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToUserExist", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckToUserExistAsync(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToAdminRules", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToAdminRulesResponse")]
        bool CheckToAdminRules(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToAdminRules", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToAdminRulesResponse")]
        System.Threading.Tasks.Task<bool> CheckToAdminRulesAsync(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToAdminPassword", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToAdminPasswordResponse")]
        bool CheckToAdminPassword(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/CheckToAdminPassword", ReplyAction="http://tempuri.org/IRegistrationContract/CheckToAdminPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckToAdminPasswordAsync(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/RegisterNewPlayer", ReplyAction="http://tempuri.org/IRegistrationContract/RegisterNewPlayerResponse")]
        WPF_User_Interface.RegistrationService.PlayerDTO RegisterNewPlayer(string nickName, WPF_User_Interface.RegistrationService.StarShipDTO startShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/RegisterNewPlayer", ReplyAction="http://tempuri.org/IRegistrationContract/RegisterNewPlayerResponse")]
        System.Threading.Tasks.Task<WPF_User_Interface.RegistrationService.PlayerDTO> RegisterNewPlayerAsync(string nickName, WPF_User_Interface.RegistrationService.StarShipDTO startShip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationContractChannel : WPF_User_Interface.RegistrationService.IRegistrationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationContractClient : System.ServiceModel.ClientBase<WPF_User_Interface.RegistrationService.IRegistrationContract>, WPF_User_Interface.RegistrationService.IRegistrationContract {
        
        public RegistrationContractClient() {
        }
        
        public RegistrationContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPF_User_Interface.RegistrationService.StarShipDTO[] GetAllShips() {
            return base.Channel.GetAllShips();
        }
        
        public System.Threading.Tasks.Task<WPF_User_Interface.RegistrationService.StarShipDTO[]> GetAllShipsAsync() {
            return base.Channel.GetAllShipsAsync();
        }
        
        public bool CheckToUserExist(string nickName) {
            return base.Channel.CheckToUserExist(nickName);
        }
        
        public System.Threading.Tasks.Task<bool> CheckToUserExistAsync(string nickName) {
            return base.Channel.CheckToUserExistAsync(nickName);
        }
        
        public bool CheckToAdminRules(string nickName) {
            return base.Channel.CheckToAdminRules(nickName);
        }
        
        public System.Threading.Tasks.Task<bool> CheckToAdminRulesAsync(string nickName) {
            return base.Channel.CheckToAdminRulesAsync(nickName);
        }
        
        public bool CheckToAdminPassword(string password) {
            return base.Channel.CheckToAdminPassword(password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckToAdminPasswordAsync(string password) {
            return base.Channel.CheckToAdminPasswordAsync(password);
        }
        
        public WPF_User_Interface.RegistrationService.PlayerDTO RegisterNewPlayer(string nickName, WPF_User_Interface.RegistrationService.StarShipDTO startShip) {
            return base.Channel.RegisterNewPlayer(nickName, startShip);
        }
        
        public System.Threading.Tasks.Task<WPF_User_Interface.RegistrationService.PlayerDTO> RegisterNewPlayerAsync(string nickName, WPF_User_Interface.RegistrationService.StarShipDTO startShip) {
            return base.Channel.RegisterNewPlayerAsync(nickName, startShip);
        }
    }
}
